/* DO NOT EDIT THIS FILE.  It contains C->PostScript communication
   definitions that were automatically generated from news.cps */

#define ps_initialize(P__0)  pprintf(PostScript, _CPS_ps_initialize, 109, P__0)
extern char _CPS_ps_initialize[];
#define ps_makefont(P__0,P__1,P__2,P__3,P__4,L__4) ( pprintf(PostScript, _CPS_ps_makefont, 13, P__0, P__1, P__2), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, 1003) > 0 && (_CPS_RETURN_ps_makefont(P__3, L__4, P__4), 1))
#define _CPS_RETURN_ps_makefont(P__3, L__4, P__4) pscanf(PostScriptInput,"d*s", P__3, L__4, P__4)
extern char _CPS_ps_makefont[];
#define ps_showtext(P__0,P__1,P__2,P__3,P__4,P__5)  pprintf(PostScript, _CPS_ps_showtext, 21, P__5, P__1, P__2, P__3, P__4, P__0)
extern char _CPS_ps_showtext[];
#define ps_mkbitmap(P__0,P__1,P__2,L__2,P__3) ( pprintf(PostScript, _CPS_ps_mkbitmap, 18, P__0, P__1, L__2, P__2), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, 1007) > 0 && (_CPS_RETURN_ps_mkbitmap(P__3), 1))
#define _CPS_RETURN_ps_mkbitmap(P__3) pscanf(PostScriptInput,"d", P__3)
extern char _CPS_ps_mkbitmap[];
#define ps_makewin(P__0,P__1) ( pprintf(PostScript, _CPS_ps_makewin, 10, P__0), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, 1004) > 0 && (_CPS_RETURN_ps_makewin(P__1), 1))
#define _CPS_RETURN_ps_makewin(P__1) pscanf(PostScriptInput,"d", P__1)
extern char _CPS_ps_makewin[];
#define ps_mapwin(P__0,P__1,P__2,P__3,P__4) ( pprintf(PostScript, _CPS_ps_mapwin, 17, P__1, P__2, P__3, P__4, P__0), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, 1005) > 0)
extern char _CPS_ps_mapwin[];
#define ps_unmapwin(P__0) ( pprintf(PostScript, _CPS_ps_unmapwin, 11, P__0), ps_checkfor(PostScriptInput, PSIO_WAIT_TAG, 1006) > 0)
extern char _CPS_ps_unmapwin[];
#define ps_setrect(P__0,P__1,P__2,P__3,P__4)  pprintf(PostScript, _CPS_ps_setrect, 18, P__1, P__2, P__3, P__4, P__0)
extern char _CPS_ps_setrect[];
#define ps_top(P__0,P__1)  pprintf(PostScript, _CPS_ps_top, 8, P__1, P__0)
extern char _CPS_ps_top[];
#define ps_focus(P__0)  pprintf(PostScript, _CPS_ps_focus, 8, P__0)
extern char _CPS_ps_focus[];
#define ps_getevent(P__0,P__1,P__2,P__3,P__4,P__5,P__6,P__7) (ps_lookingat(PostScriptInput, 1002) > 0 && (_CPS_RETURN_ps_getevent(P__0, P__1, P__2, P__3, P__7, P__6, P__5, P__4), 1))
#define _CPS_RETURN_ps_getevent(P__0, P__1, P__2, P__3, P__7, P__6, P__5, P__4) pscanf(PostScriptInput,"dddddddd", P__0, P__1, P__2, P__3, P__7, P__6, P__5, P__4)
#define ps_strokeline(P__0,P__1,P__2,P__3,P__4,P__5,P__6)  pprintf(PostScript, _CPS_ps_strokeline, 25, P__0, P__1, P__2, P__5, P__6, P__3, P__4)
extern char _CPS_ps_strokeline[];
#define ps_strokerect(P__0,P__1,P__2,P__3,P__4,P__5,P__6)  pprintf(PostScript, _CPS_ps_strokerect, 25, P__0, P__1, P__2, P__3, P__4, P__5, P__6)
extern char _CPS_ps_strokerect[];
#define ps_fillrect(P__0,P__1,P__2,P__3,P__4,P__5)  pprintf(PostScript, _CPS_ps_fillrect, 21, P__0, P__1, P__2, P__3, P__4, P__5)
extern char _CPS_ps_fillrect[];
#define ps_strokeoval(P__0,P__1,P__2,P__3,P__4,P__5,P__6)  pprintf(PostScript, _CPS_ps_strokeoval, 25, P__0, P__1, P__2, P__3, P__4, P__5, P__6)
extern char _CPS_ps_strokeoval[];
#define ps_filloval(P__0,P__1,P__2,P__3,P__4,P__5)  pprintf(PostScript, _CPS_ps_filloval, 21, P__0, P__1, P__2, P__3, P__4, P__5)
extern char _CPS_ps_filloval[];
#define ps_strokerrect(P__0,P__1,P__2,P__3,P__4,P__5,P__6,P__7)  pprintf(PostScript, _CPS_ps_strokerrect, 28, P__0, P__1, P__2, P__3, P__4, P__5, P__6, P__7)
extern char _CPS_ps_strokerrect[];
#define ps_fillrrect(P__0,P__1,P__2,P__3,P__4,P__5,P__6)  pprintf(PostScript, _CPS_ps_fillrrect, 24, P__0, P__1, P__2, P__3, P__4, P__5, P__6)
extern char _CPS_ps_fillrrect[];
#define ps_openpolygon(P__0,P__1)  pprintf(PostScript, _CPS_ps_openpolygon, 16, P__0, P__1)
extern char _CPS_ps_openpolygon[];
#define ps_curveto(P__0,P__1,P__2,P__3,P__4,P__5)  pprintf(PostScript, _CPS_ps_curveto, 14, P__0, P__1, P__2, P__3, P__4, P__5)
extern char _CPS_ps_curveto[];
#define ps_strokepolygon(P__0,P__1,P__2)  pprintf(PostScript, _CPS_ps_strokepolygon, 20, P__0, P__1, P__2)
extern char _CPS_ps_strokepolygon[];
#define ps_fillpolygon(P__0,P__1)  pprintf(PostScript, _CPS_ps_fillpolygon, 16, P__0, P__1)
extern char _CPS_ps_fillpolygon[];
#define ps_scrollrect(P__0,P__1,P__2,P__3,P__4,P__5)  pprintf(PostScript, _CPS_ps_scrollrect, 23, P__4, P__5, P__0, P__1, P__2, P__3)
extern char _CPS_ps_scrollrect[];
#define ps_showbitmap(P__0,P__1,P__2,P__3,P__4,P__5,P__6)  pprintf(PostScript, _CPS_ps_showbitmap, 25, P__6, P__4, P__5, P__2, P__3, P__0, P__1)
extern char _CPS_ps_showbitmap[];
#define ps_setclip(P__0,P__1,P__2,P__3)  pprintf(PostScript, _CPS_ps_setclip, 16, P__0, P__1, P__2, P__3)
extern char _CPS_ps_setclip[];
#ifndef PSMACROS_H
#include <NeWS/psmacros.h>		/* standard cdef macros */
#endif
