/* DO NOT EDIT THIS FILE.  It contains C->PostScript communication
   initializations that were automatically generated from news.cps */

char _CPS_ps_initialize[] = "/DoneTag\201\003\351\264/EventTag\201\003\352\264/MkWinTag\201\003\354\264/MkFontTag\201\003\353\264/MapWinTag\201\003\355\264/UnMapWinTag\201\003\356\264/MkBitmapTag\201\003\357\264%sLoadFile ";
char _CPS_ps_makefont[] = "%d%d%dmkfont ";
char _CPS_ps_showtext[] = "%s%d%d%d%d%dshowtext ";
char _CPS_ps_mkbitmap[] = "%d%d%*smakebitmap ";
char _CPS_ps_makewin[] = "%dmakewin ";
char _CPS_ps_mapwin[] = "%d%d%d%d%dmapwin ";
char _CPS_ps_unmapwin[] = "%dunmapwin ";
char _CPS_ps_setrect[] = "%d%d%d%d%dsetrect ";
char _CPS_ps_top[] = "%d%dTop ";
char _CPS_ps_focus[] = "%dFocus ";
char _CPS_ps_strokeline[] = "%d%d%d%d%d%d%dstrokeline ";
char _CPS_ps_strokerect[] = "%d%d%d%d%d%d%dstrokerect ";
char _CPS_ps_fillrect[] = "%d%d%d%d%d%dfillrect ";
char _CPS_ps_strokeoval[] = "%d%d%d%d%d%d%dstrokeoval ";
char _CPS_ps_filloval[] = "%d%d%d%d%d%dfilloval ";
char _CPS_ps_strokerrect[] = "%d%d%d%d%d%d%d%dstrokerrect ";
char _CPS_ps_fillrrect[] = "%d%d%d%d%d%d%dfillrrect ";
char _CPS_ps_openpolygon[] = "%d%dopenpolygon ";
char _CPS_ps_curveto[] = "%d%d%d%d%d%d\2466";
char _CPS_ps_strokepolygon[] = "%d%d%dstrokepolygon ";
char _CPS_ps_fillpolygon[] = "%d%dfillpolygon ";
char _CPS_ps_scrollrect[] = "%d%d%d%d%d%dscrollrect ";
char _CPS_ps_showbitmap[] = "%d%d%d%d%d%d%dshowbitmap ";
char _CPS_ps_setclip[] = "%d%d%d%dsetclip ";
