BMCUT   =   bmcut
ALLIM   =  1.im 2.im 3.im 5.im 6.im 7.im 


all:    $(ALLIM)
	
1.im:    1.image
	$(BMCUT) 1.image 40 28 > $@

2.im:    2.image
	$(BMCUT) 2.image 40 28 > $@

3.im:    3.image
	$(BMCUT) 3.image 40 28 > $@

5.im:    5.image
	$(BMCUT) 5.image 40 28 > $@

6.im:    6.image
	$(BMCUT) 6.image 40 28 > $@

7.im:    7.image
	$(BMCUT) 7.image 40 28 > $@

clean:
	rm -f core

clobber:    clean

